# Generated by Django 2.0.5 on 2018-12-27 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='thread',
            new_name='name',
        ),
    ]
